// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0D62IDQmpDieGx7OEha7bFeaJuvHzjFE',
    appId: '1:267910282750:web:66cbd763a86766476f54af',
    messagingSenderId: '267910282750',
    projectId: 'unisec-e36e1',
    authDomain: 'unisec-e36e1.firebaseapp.com',
    storageBucket: 'unisec-e36e1.firebasestorage.app',
    measurementId: 'G-1HCH7PZ8ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDKt54pLahe8SXEtwS7EHEHPf4lObMnKQ',
    appId: '1:267910282750:android:29017a5ae36387536f54af',
    messagingSenderId: '267910282750',
    projectId: 'unisec-e36e1',
    storageBucket: 'unisec-e36e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMT4e-JbWIGPmrOOpLqcEqsHd1OYKct_w',
    appId: '1:267910282750:ios:410ae7ebb0b387396f54af',
    messagingSenderId: '267910282750',
    projectId: 'unisec-e36e1',
    storageBucket: 'unisec-e36e1.firebasestorage.app',
    androidClientId: '267910282750-0n1u50d3vgr2euot9jeb3a1jr7e3r1h1.apps.googleusercontent.com',
    iosClientId: '267910282750-1edljekj2eul0lajkvo1h7o5b60kjhq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMT4e-JbWIGPmrOOpLqcEqsHd1OYKct_w',
    appId: '1:267910282750:ios:410ae7ebb0b387396f54af',
    messagingSenderId: '267910282750',
    projectId: 'unisec-e36e1',
    storageBucket: 'unisec-e36e1.firebasestorage.app',
    androidClientId: '267910282750-0n1u50d3vgr2euot9jeb3a1jr7e3r1h1.apps.googleusercontent.com',
    iosClientId: '267910282750-1edljekj2eul0lajkvo1h7o5b60kjhq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0D62IDQmpDieGx7OEha7bFeaJuvHzjFE',
    appId: '1:267910282750:web:04d133b47482bfd56f54af',
    messagingSenderId: '267910282750',
    projectId: 'unisec-e36e1',
    authDomain: 'unisec-e36e1.firebaseapp.com',
    storageBucket: 'unisec-e36e1.firebasestorage.app',
    measurementId: 'G-53TNHC40RS',
  );
}
