"""ÖSYM/YÖK-Atlas üniversite adı → app id eşlemesi (tek doğruluk kaynağı).

csv_to_json_parser.py ve xlsx_2025_parser.py buradan import eder.
Yeni üniversite eklerken v2_generate_seed.py çıktısındaki
v2_uni_mapping_additions.json ile senkron tutulmalı.
"""

UNI_MAPPING = {
    'İSTANBUL TEKNİK ÜNİVERSİTESİ': 'itu',
    'İSTANBUL ÜNİVERSİTESİ': 'istanbul_uni',
    'YILDIZ TEKNİK ÜNİVERSİTESİ': 'yildiz_teknik',
    'ORTA DOĞU TEKNİK ÜNİVERSİTESİ': 'odtu',
    'HACETTEPE ÜNİVERSİTESİ': 'hacettepe',
    'ANKARA ÜNİVERSİTESİ': 'ankara_uni',
    'GAZİ ÜNİVERSİTESİ': 'gazi',
    'EGE ÜNİVERSİTESİ': 'ege',
    'DOKUZ EYLÜL ÜNİVERSİTESİ': 'dokuz_eylul',
    'AKDENİZ ÜNİVERSİTESİ': 'akdeniz',
    'ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ': 'alanya',
    'ANADOLU ÜNİVERSİTESİ': 'anadolu',
    'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ': 'ogu',
    'ESKİŞEHİR TEKNİK ÜNİVERSİTESİ': 'estu',
    'BURSA ULUDAĞ ÜNİVERSİTESİ': 'uludag',
    'BURSA TEKNİK ÜNİVERSİTESİ': 'btu',
    'ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ': 'comu',
    'SİVAS CUMHURİYET ÜNİVERSİTESİ': 'cumhuriyet',
    'SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ': 'sivas_btu',
    'KARADENİZ TEKNİK ÜNİVERSİTESİ': 'ktu',
    'TRABZON ÜNİVERSİTESİ': 'trabzon_uni',
    'MERSİN ÜNİVERSİTESİ': 'mersin_uni',
    'TARSUS ÜNİVERSİTESİ': 'tarsus',
    'MARMARA ÜNİVERSİTESİ': 'marmara',
    'ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ': 'hacibayram',
    'İZMİR DEMOKRASİ ÜNİVERSİTESİ': 'izmir_demokrasi',
    'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ': 'izmir_katipcelebi',
    'İSTANBUL AYDIN ÜNİVERSİTESİ': 'aydin',
    'İSTANBUL GELİŞİM ÜNİVERSİTESİ': 'gelisim',
    'İSTANBUL MEDİPOL ÜNİVERSİTESİ': 'medipol',
    'HİTİT ÜNİVERSİTESİ': 'hitit',
    'ERCİYES ÜNİVERSİTESİ': 'erciyes',
    'İNÖNÜ ÜNİVERSİTESİ': 'inonu',
    'ONDOKUZ MAYIS ÜNİVERSİTESİ': 'omu',
    'SELÇUK ÜNİVERSİTESİ': 'selcuk',
    'KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ': 'dpu',
    'KOCAELİ ÜNİVERSİTESİ': 'kocaeli',
    'SAKARYA ÜNİVERSİTESİ': 'sakarya',
    'BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ': 'ibu',
    'ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ': 'beun',
    'VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ': 'yyu',
    'ATATÜRK ÜNİVERSİTESİ': 'atauni',
    'GAZİANTEP ÜNİVERSİTESİ': 'gantep',
    'ÇUKUROVA ÜNİVERSİTESİ': 'cu',
    'PAMUKKALE ÜNİVERSİTESİ': 'pau',
    'KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ': 'ksu',
    'MANİSA CELÂL BAYAR ÜNİVERSİTESİ': 'cbu',
    'SÜLEYMAN DEMİREL ÜNİVERSİTESİ': 'sdu',
    'KARABÜK ÜNİVERSİTESİ': 'karabuk',
    'TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ': 'gop',
    'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ': 'asbu',
    'ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ': 'aybu',
    'ATILIM ÜNİVERSİTESİ': 'atilim',
    'BAHÇEŞEHİR ÜNİVERSİTESİ': 'bahcesehir',
    'BAŞKENT ÜNİVERSİTESİ': 'baskent',
    'BOĞAZİÇİ ÜNİVERSİTESİ': 'bogazici',
    'GALATASARAY ÜNİVERSİTESİ': 'galatasaray',
    'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ': 'bilkent',
    'İSTANBUL BİLGİ ÜNİVERSİTESİ': 'bilgi',
    'İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA': 'iuc',
    'İZMİR EKONOMİ ÜNİVERSİTESİ': 'izmir_ekonomi',
    'İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ': 'iyte',
    'KADİR HAS ÜNİVERSİTESİ': 'kadir_has',
    'KOÇ ÜNİVERSİTESİ': 'koc',
    'MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ': 'msgsu',
    'ÖZYEĞİN ÜNİVERSİTESİ': 'ozyegin',
    'SABANCI ÜNİVERSİTESİ': 'sabanci',
    'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ': 'sbu',
    'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ': 'tobb_etu',
    'TÜRK-ALMAN ÜNİVERSİTESİ': 'turk_alman',
    'YAŞAR ÜNİVERSİTESİ': 'yasar',
    'YEDİTEPE ÜNİVERSİTESİ': 'yeditepe',
    'BALIKESİR ÜNİVERSİTESİ': 'balikesir_uni',
    'AYDIN ADNAN MENDERES ÜNİVERSİTESİ': 'adu',
    'HARRAN ÜNİVERSİTESİ': 'harran',
    'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ': 'msku',
    'FIRAT ÜNİVERSİTESİ': 'firat',
    'AFYON KOCATEPE ÜNİVERSİTESİ': 'aku',
    'DİCLE ÜNİVERSİTESİ': 'dicle',
    'GİRESUN ÜNİVERSİTESİ': 'giresun_uni',
    'BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ': 'maku',
    'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ': 'nevu',
    'TRAKYA ÜNİVERSİTESİ': 'trakya',
    'KASTAMONU ÜNİVERSİTESİ': 'kastamonu_uni',
    'YOZGAT BOZOK ÜNİVERSİTESİ': 'yobu',
    'GÜMÜŞHANE ÜNİVERSİTESİ': 'gumushane_uni',
    'HATAY MUSTAFA KEMAL ÜNİVERSİTESİ': 'mku',
    'AMASYA ÜNİVERSİTESİ': 'amasya_uni',
    'TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ': 'nku',
    'BİNGÖL ÜNİVERSİTESİ': 'bingol_uni',
    'ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ': 'ebyu',
    'DÜZCE ÜNİVERSİTESİ': 'duzce_uni',
    'KIRIKKALE ÜNİVERSİTESİ': 'kku',
    'ADIYAMAN ÜNİVERSİTESİ': 'adiyaman_uni',
    'ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ': 'isubu',
    'NECMETTİN ERBAKAN ÜNİVERSİTESİ': 'erbakan',
    'KIRKLARELİ ÜNİVERSİTESİ': 'klu',
    'MARDİN ARTUKLU ÜNİVERSİTESİ': 'artuklu',
    'KAFKAS ÜNİVERSİTESİ': 'kafkas',
    'SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ': 'subu',
    'NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ': 'ohu',
    'BİTLİS EREN ÜNİVERSİTESİ': 'bitlis_eren',
    'KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ': 'kaeu',
    'AKSARAY ÜNİVERSİTESİ': 'aksaray_uni',
    'ARTVİN ÇORUH ÜNİVERSİTESİ': 'acu',
}
